openapi: 3.0.0
info:
  title: monolith-nodejs
  version: 0.0.0
  description: Rest API
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
